version: '3.8'

services:

  # db:
    # image: postgres
    # container_name: postgres_db
    # restart: always
    # environment:
    #   POSTGRES_USER: myuser
    #   POSTGRES_PASSWORD: mysecretpassword
    #   POSTGRES_DB: mydb
    # volumes:
    #   - pgdata:/var/lib/postgresql/data
    # networks:
    #   mynet:
    #     ipv4_address: 172.16.0.3
    # ports:
    #   - "5432:5432"

  db:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: myuser
      MONGO_INITDB_ROOT_PASSWORD: mysecretpassword
    volumes:
      - .mongodata:/data/db
    networks:
      mynet:
        ipv4_address: 172.16.0.3
    ports:
      - "27017:27017"


  server:
    build: ./server
    container_name: flask_server
    restart: always
    networks:
      mynet:
        ipv4_address: 172.16.0.2
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      # DATABASE_URL: postgres://myuser:mysecretpassword@db:5432/mydb
      MONGO_URI: mongodb://myuser:mysecretpassword@db:27017/

    volumes:
      - ./server:/app

  # client:
  #   image: nginx:alpine
  #   container_name: web_client
  #   restart: always
  #   volumes:
  #     - /Users/yles94214/Desktop/Final_Project/client:/usr/share/nginx/html:ro
  #   ports:
  #     - "8080:80"

volumes:
  pgdata:
  mongodata:

networks:
  mynet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/16